hostname: R4
interfaces:
  - name: g1.14
    ip: 155.1.14.4
    mask: 255.255.255.0
    desc: Main connection to network 155.1.14.0/24
    vlan: 14
    shutdown: false
  - name: loopback0
    ip: 150.1.4.4
    mask: 255.255.255.255
    desc: Loopback address
    shutdown: false

ospf:
    process_id: 1
    router_id: 150.1.4.4
    networks:
     - network: 150.1.4.4
       wildcard: 0.0.0.0
       area: 0
     - network: 155.1.14.4
       wildcard: 0.0.0.0
       area: 0
