hostname: R3
interfaces:
  - name: g1.13
    ip: 155.1.13.3
    mask: 255.255.255.0
    desc: Main connection to network 155.1.13.0/24
    vlan: 13
    shutdown: false
  - name: loopback0
    ip: 150.1.3.3
    mask: 255.255.255.255
    desc: Loopback address
    shutdown: false

ospf:
    process_id: 1
    router_id: 150.1.3.3
    networks:
     - network: 150.1.3.3
       wildcard: 0.0.0.0
       area: 0
     - network: 155.1.13.3
       wildcard: 0.0.0.0
       area: 0
