hostname: R1
interfaces:
  - name: g1.12
    ip: 155.1.12.1
    mask: 255.255.255.0
    desc: Main connection to network 155.1.12.0/24
    vlan: 12
    shutdown: false
  - name: g1.13
    ip: 155.1.13.1
    mask: 255.255.255.0
    desc: Main connection to network 155.1.13.0/24
    vlan: 13
    shutdown: false
  - name: g1.14
    ip: 155.1.14.1
    mask: 255.255.255.0
    desc: Main connection to network 155.1.14.0/24
    vlan: 14
    shutdown: false
  - name: loopback0
    ip: 150.1.1.1
    mask: 255.255.255.255
    desc: Loopback address
    shutdown: false
ospf:
    process_id: 1
    router_id: 150.1.1.1
    networks:
     - network: 150.1.1.1
       wildcard: 0.0.0.0
       area: 0
     - network: 155.1.12.2
       wildcard: 0.0.0.0
       area: 0
