hostname: R2
interfaces:
  - name: g1.12
    ip: 155.1.12.2
    mask: 255.255.255.0
    desc: Main connection to network 155.1.12.0/24
    vlan: 12
    shutdown: false
  - name: loopback0
    ip: 150.1.2.2
    mask: 255.255.255.255
    desc: Loopback address
    shutdown: false

ospf:
    process_id: 1
    router_id: 150.1.2.2
    networks:
     - network: 150.1.2.2
       wildcard: 0.0.0.0
       area: 0
     - network: 155.1.12.2
       wildcard: 0.0.0.0
       area: 0
